openapi: 3.0.3
info:
  title: Todo Frontend API Client
  description: API client contract for Next.js frontend interacting with Todo backend
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.todoapp.com
    description: Production server
paths:
  /auth/register:
    post:
      summary: Register new user
      description: Creates a new user account and returns authentication tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                name:
                  type: string
                  description: User's display name
                password:
                  type: string
                  format: password
                  minLength: 8
                  description: User's password
              required:
                - email
                - name
                - password
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT access token
                  token_type:
                    type: string
                    description: Type of token (usually "bearer")
                  user_id:
                    type: string
                    description: Unique identifier of the created user
        '400':
          description: Bad request - invalid input data
        '409':
          description: Conflict - user with this email already exists
  /auth/login:
    post:
      summary: Authenticate user
      description: Authenticates a user and returns authentication tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT access token
                  token_type:
                    type: string
                    description: Type of token (usually "bearer")
                  user_id:
                    type: string
                    description: Unique identifier of the authenticated user
        '401':
          description: Unauthorized - incorrect email or password
  /auth/logout:
    post:
      summary: Logout user
      description: Logs out the current user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Logout successful
  /api/{user_id}/tasks:
    get:
      summary: Get user's tasks
      description: Retrieve all tasks for the authenticated user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user whose tasks to retrieve
          schema:
            type: string
        - name: completed
          in: query
          required: false
          description: Filter tasks by completion status
          schema:
            type: boolean
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - invalid or expired token
        '403':
          description: Forbidden - user trying to access another user's tasks
    post:
      summary: Create new task
      description: Create a new task for the authenticated user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user creating the task
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreateRequest'
      security:
        - BearerAuth: []
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - invalid or expired token
        '403':
          description: Forbidden - user trying to create task for another user
        '422':
          description: Unprocessable entity - invalid input data
  /api/{user_id}/tasks/{id}:
    get:
      summary: Get task details
      description: Retrieve details of a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user who owns the task
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID of the task to retrieve
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - invalid or expired token
        '403':
          description: Forbidden - user trying to access another user's task
        '404':
          description: Task not found
    put:
      summary: Update task
      description: Update details of an existing task
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user who owns the task
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID of the task to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdateRequest'
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - invalid or expired token
        '403':
          description: Forbidden - user trying to update another user's task
        '404':
          description: Task not found
        '422':
          description: Unprocessable entity - invalid input data
    delete:
      summary: Delete task
      description: Delete a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user who owns the task
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID of the task to delete
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - invalid or expired token
        '403':
          description: Forbidden - user trying to delete another user's task
        '404':
          description: Task not found
  /api/{user_id}/tasks/{id}/complete:
    patch:
      summary: Toggle task completion
      description: Update the completion status of a task
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user who owns the task
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID of the task to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                completed:
                  type: boolean
                  description: New completion status for the task
              required:
                - completed
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Task completion status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - invalid or expired token
        '403':
          description: Forbidden - user trying to update another user's task
        '404':
          description: Task not found
        '422':
          description: Unprocessable entity - invalid input data

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the task
        user_id:
          type: string
          description: ID of the user who owns the task
        title:
          type: string
          description: Title of the task
        description:
          type: string
          description: Detailed description of the task
        completed:
          type: boolean
          description: Whether the task is completed
        created_at:
          type: string
          format: date-time
          description: Timestamp when the task was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the task was last updated
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
    
    TaskCreateRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
        description:
          type: string
          maxLength: 1000
          nullable: true
        completed:
          type: boolean
          default: false
      required:
        - title
      additionalProperties: false
    
    TaskUpdateRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
        description:
          type: string
          maxLength: 1000
          nullable: true
        completed:
          type: boolean
      additionalProperties: false